### PR TITLE
[TR] PIM-4928 : minor changes to 1.3 - 1.4 migration instructions

### PR DESCRIPTION
**Pull request by jmleroux**
- Fix Download URL
- Need to clear cache before composer update because of Symfony version bump.

### CODE REVIEW

**Comment by jjanvier** [comment]
GTM

**Comment by jjanvier** [comment]
think about the `rm -rf app/cache/*` for EE standard too please

**Comment by jmleroux** [comment]
@jjanvier it's on the way.
Thx for the reminder :+1:

**Comment by skeleton** [comment]
GTM

**Comment by nototlt** [comment]
GTM

**Comment by jmleroux** [comment]
EE corresponding PR : https://github.com/akeneo/pim-enterprise-standard/pull/106

**Pull request merged**
